name: rename-index
on: workflow_dispatch
permissions:
  contents: write
jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git mv space-3.html index.html
          git commit -m "Rename space-3.html to index.html"
          git push
